export const data = {
  first_name: "",
  last_name: "",
  middle_name: "",
  street_address: "",
  apartment_unit: "",
  city: "",
  state: "",
  phone: "",
  email: "",
  date_available: "",
  social_security_no: "",
  desired_salary: "$",
  postion_applied_for: "",
  citizen_of_united_state: "",
  autorized_to_work: "",
  have_you_been_convited_of_a_felony: "",
  yes_have_you_been_convited_of_a_felony: "",

  high_school: "",
  high_school_address: "",
  high_school_from: "",
  high_school_to: "",
  did_you_graduate_high_school: "",
  degree: "",
  college_school: "",
  college_address: "",
  college_school_from: "",
  college_school_to: "",
  did_you_graduate_college: "",
  diploma: "",

  refeerence1_full_name: "",
  refeerence1_relationship: "",
  refeerence1_conmpany: "",
  refeerence1_phone: "",
  refeerence1_full_address: "",
  refeerence2_full_name: "",
  refeerence2_company: "",
  refeerence2_phone: "",
  refeerence2_full_address: "",
  refeerence3_full_name: "",
  refeerence3_company: "",
  refeerence3_phone: "",
  refeerence3_full_address: "",

  prev_enployment_conmpany: "",
  prev_enployment_phone: "",
  prev_enployment_address: "",
  prev_enployment_supervisor: "",
  prev_enployment_job_title: "",
  prev_enployment_starting_salary: "$",
  prev_enployment_Ending_salary: "$",
  prev_enployment_from: "",
  prev_enployment_to: "",
  reason_for_leaving: "",
  contact_your_prev_supervisor_for_a_reference: "",

  military_service_branch: "",
  military_service_from: "",
  military_service_rank: "",
  military_service_type_of_discharge: "",
  other_than_honorable: "",

  accept: "",
};
